services:
  hackintosh:
#    privileged: true
    environment:
      - OSX_COMMANDS=echo 'alpine' | sudo -v -S && /bin/bash -c "$$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" <<< '\n' && echo 'alpine' | sudo -v -S && brew install fastlane
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/hackintosh
    ports:
      - "50922:10022"
    devices:
      - "/dev/kvm"
    stdin_open: true
    tty: true
